- pwd
- 'export STEAMDIR=$PWD'

- steam_deps:
  - 'echo "current dir: " && pwd'
  - cd src/deps/catkin
  - build:
      - pwd
      - catkin config --extend /opt/ros/install
      - catkin config -a --cmake-args -DCMAKE_BUILD_TYPE=Release
      - catkin build --no-status

- steam:
  - 'echo "current dir: " && pwd'
  - build:
    - pwd
    - catkin init
    - catkin config --no-cmake-args
    - catkin config --extend ${STEAMDIR}/devel/deps
    - catkin config -a --cmake-args -DCMAKE_BUILD_TYPE=Release
    - catkin config --merge-devel
    - catkin build --no-status
  - test:
    - export TERM=xterm
    - cd devel/lib/steam
    - ./steam_unit_tests
  - clean:
    - catkin clean -y
